### ISSUE TITLE
Comment code so beginners can understand it

### ISSUE THREAD

**Issue by 5HT2** [FrequencyX4/CTBot#5]

**Comment by mouncg** [comment]
ok, I will comment on things like the censor plugin.

**Comment by 5HT2** [comment]
Oh I self assigned this lol. I was gonna do it

**Comment by mouncg** [comment]
welp, lol I am doing `cogs/appeals.py`

**Comment by mouncg** [comment]
and I am commenting on EVERY single line lol

**Comment by mouncg** [comment]
done appeals

**Comment by mouncg** [comment]
gonna start on `cogs/autoresponse.py`

**Comment by 5HT2** [comment]
For future reference: https://github.com/FrequencyX4/CTBot/commit/4d15169685799e10d73178000f66f50fe7f39a10

**Comment by mouncg** [comment]
yea lol
