### ISSUE TITLE
Notify user that the word they are trying to say is not allowed

### ISSUE THREAD

**Issue by 5HT2** [FrequencyX4/CTBot#6]
**Describe the solution you'd like**
It would be nice to tell the user that the word they're trying to say is blocked, preferably without saying the word itself in the reply. This prevents them being confused as to why their message is deleted.

**Describe alternatives you've considered**
Telling them manually if they ask, but that's not possible unless you were actively reading the chat

**Comment by korochun** [comment]
Done https://github.com/FrequencyX4/CTBot/commit/7b26ab880af9fd9f2e5cbea417e6e780124dcde8.

**Comment by mouncg** [comment]
... why was this created, there is already a plugin to do this at some point

**Comment by mouncg** [comment]
eh, but it is much slicker in this one tho ;)
